name: Deploy Angular App to S3 Bucket and CloudFront

on:
  push:
    branches:
      - angular-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --output-path=dist/angular-app

    # - name: List the dir
    #   run: |
    #     ls -ltr
    #     cd dist
    #     ls -ltr

    # - name: Create CloudFront distribution
    #   id: create_cloudfront
    #   run: |
    #     DISTRIBUTION_ID=$(aws cloudfront create-distribution --origin-domain-name ${{ github.event.inputs.bucket_name || 'anguler-s3-static-website' }}.s3.amazonaws.com \
    #     --default-root-object index.html --output json | jq -r '.Distribution.Id')
    #     echo "DISTRIBUTION_ID=$DISTRIBUTION_ID" >> $GITHUB_ENV
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: ${{ secrets.AWS_REGION }}

    # - name: Deploy to S3 bucket
    #   uses: jakejarvis/s3-sync-action@v0.4.0
    #   with:
    #     args: --acl public-read --delete
    #   env:
    #     AWS_S3_BUCKET: ${{ github.event.inputs.bucket_name || 'anguler-s3-static-website' }}
    #     AWS_REGION: "us-east-1"  
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     SOURCE_DIR: "dist/angular-app"
       
    # # - name: Deploy to S3 bucket
    # #   uses: jakejarvis/s3-sync-action@v0.4.0
    # #   with:
    # #     args: --delete
    # #   env:
    # #     AWS_S3_BUCKET: "anguler-s3-static-website"
    # #     AWS_REGION: "us-east-1"
    # #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    # #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # - name: Create CloudFront invalidation
    #   run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
